name: Deploy to Shared Host
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy via FTP
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ai.redlionsalvage.net
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: ./
        remoteDir: /ai.redlionsalvage.net/
    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp
    - name: Remove Old Folder
      run: lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -e "set ssl:verify-certificate no; rm -rf /ai.redlionsalvage.net/ai.redlionsalvage.net; bye" ai.redlionsalvage.net