name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test and Deploy to Server via FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_REMOTE_DIR: /home/username/public_html/ai.redlionsalvage.net  # Replace 'username'
        run: |
          echo "Testing FTP connection to $FTP_HOST"
          curl --verbose ftp://"$FTP_HOST" --user "$FTP_USERNAME:$FTP_PASSWORD" --ftp-method singlecwd && echo "FTP test succeeded" || {
            echo "FTP test failed: $?";
            exit 1;
          }
          echo "Deploying with lftp"
          lftp -u "$FTP_USERNAME,$FTP_PASSWORD" "$FTP_HOST" <<EOF
          set ftp:passive-mode true
          mirror -R --exclude-glob .git* --exclude-glob .github/ --exclude .gitignore --exclude composer.lock ./ $FTP_REMOTE_DIR
          quit
          EOF
          echo "Deployment complete"
