name: Deploy to Shared Host
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ai.redlionsalvage.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /ai.redlionsalvage.net/
        timeout: 120000  # 120s to handle slow server
        exclude: |
          **/.git/**
          **/.github/**
          **/node_modules/**