name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug Secrets and Test FTP Connection
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "FTP_HOST is set to: $FTP_HOST"  # Will mask if sensitive
          echo "FTP_USERNAME length: ${#FTP_USERNAME}"  # Shows length, not value
          echo "FTP_PASSWORD length: ${#FTP_PASSWORD}"  # Shows length, not value
          if [ -z "$FTP_HOST" ] || [ -z "$FTP_USERNAME" ] || [ -z "$FTP_PASSWORD" ]; then
            echo "One or more secrets are empty - please check GitHub Secrets"
            exit 1
          fi
          echo "Testing FTP connection to web26.us.cloudlogin.co (hardcoded)"
          curl --verbose ftp://web26.us.cloudlogin.co --user "$FTP_USERNAME:$FTP_PASSWORD" --ftp-method singlecwd && echo "FTP test succeeded" || {
            echo "FTP test failed: $?";
            exit 1;
          }
          echo "Test complete - secrets and connection verified"
