name: Deploy to Server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy via FTP
        uses: wlixn/FTP-Upload@v2.0
        with:
          ftp-host: ${{ secrets.FTP_HOST }}
          ftp-user: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          source-path: "*"  # Upload all repo contents directly
          target-path: "/www/ai.redlionsalvage.net/"
          overwrite: true  # Overwrite existing files
