name: Deploy to Shared Host
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy via FTP
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ai.redlionsalvage.net
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: ./
        remoteDir: /ai.redlionsalvage.net/