name: Deploy to Shared Host
on:
  push:
    branches:
      - main  # Change this to your default branch if it’s not ‘main’ (e.g., ‘master’)
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.yourdomain.com  # Replace with your FTP host
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./  # Source folder in your repo (root by default)
        server-dir: /public_html/  # Destination folder on your server
        exclude: |
          **/.git*
          **/.github/**
          **/node_modules/**
