name: Update YardMaster Report

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Generate Report Parts
        run: |
          python generate_report.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ".github/YardMaster Analysis ReportPart*"
          git pull --rebase origin main
          git diff --staged --quiet || git commit -m "Update report parts with latest changes - $(date +%Y-%m-%d)"
          git push